### ISSUE TITLE
Layout components (Box, Grid) in Figma?

### ISSUE THREAD

**Issue by gpersonsqw** [mui/mui-design-kits#184]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Hi all -- Is there any way to replicate the MUI layout components in Figma? We're looking to be able to exactly replicate spacing/alignment and other box/grid settings between Figma and React, and can't find the grid/box in the figma component library. Are there components for these, and if not, is there a way to replicate the box/grid settings within Figma?

**Comment by adrianmanea** [comment]
This is an interesting request. Personally, I use `Box` and `Grid` frames frequently in Figma. However, I create them contextually because it can be time-consuming to detach an empty instance each time. This is because you cannot simply add anything inside a component once it is defined, unless you have an instance that can be switched.

Here's a custom component I created using a Spacer component, Box and Grid frames.

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/5917515/237053905-dffe8b84-4d74-485c-b501-647fd708a329.png">

**Comment by faner11** [comment]
We'll be using the Grid in our Antd project, so maybe MUI can learn from it!
https://www.figma.com/file/FARXpM1z2tHZWxKg5ndnOM/%5BPreview%5D-Ant-Design-System-for-Figma-5.7?type=design&node-id=1233-45222&mode=design&t=96EDPioUMVcpmjIs-0

**Comment by adrianmanea** [comment]
We've had the Stack component for a while now 👍 

https://www.figma.com/file/7uikYyOkYdO9PPaOkhQd6n/MUI-for-Figma-v5.14.0---Material-UI-(Full-Preview)?type=design&node-id=11477-166906&mode=design&t=LW4Vk6NhEdsPZ2Ea-4
