### ISSUE TITLE
[question]  Working with nested instances ("instance slot") within components - can I make custimization less time consuming?

### ISSUE THREAD

**Issue by jgobyte** [mui/mui-design-kits#237]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

Can you advice the best way to add new custom content to Card Components in Figma?

For now to a customized card content I need to create a separate Master component with the content so I can swap it with a place holder instance from the library and it's super painful work with.

In the hints that you provide to components there is one like this 
<img width="659" alt="Screenshot 2023-09-06 at 22 48 01" src="https://github.com/mui/mui-design-kits/assets/144065870/5523a889-27e5-4baa-810f-2529955fafaa">

However if I detach this instance the whole Card component will be detached from the MUI library - is this still something you would advice to do to speedup working with Cards? I try to avoid detaching components generally.

### Your environment 🌎

Material UI v5.14.0

**Comment by adrianmanea** [comment]
I believe the decision depends on how much control you want over your components. If you anticipate customizing <Card> or <CardContent>, such as changing the padding, it's better to use them as components rather than detaching them using the method you mentioned by creating a master component with only the card contents.

Alternatively, for simpler cases, you can use the <Stack> component to arrange your card content.
