### ISSUE TITLE
Can't download the latest version?

### ISSUE THREAD

**Issue by Arno-Sympower** [mui/mui-design-kits#342]
### The problem in depth

I've bought a Mui Design Kit for Figma license, but in the downloads section when I click on download It gives the message: "Sorry, this download has expired [Go to shop](https://store-wp.mui.com/)".

Does the license expire?

### Your environment

Firefox browser.

**Search keywords**: License

**Comment by zannager** [comment]
@Arno-Sympower access to the portal is disabled once your license support and update have expired. However, you are eligible to get the last version update before your license expiration, please send as an email through sales@mui.com. Otherwise, if you wish to get the latest version, you need to renew at a discounted price.

Please send your request via sales@mui.com to assist you further.
