### ISSUE TITLE
Difference between paid MUI library and free version

### ISSUE THREAD

**Issue by steve-merrick** [mui/mui-design-kits#360]
### The problem in depth

Hi,

I am finding two MUI component libraries:

1. MUI for Figma - https://mui.com/store/items/figma-react/
2. Material 3 Design Kit - https://www.figma.com/community/file/1035203688168086460

What is the difference between these two? I see that #1 is $79 and #2 is free. What additional features/capabilities do I get with the paid version?

**Search keywords**: figma

**Comment by adrianmanea** [comment]
Hi Steve, thanks for reaching out! In the community version of our product, you'll have access to pre-built instances and a limited number of (!source) components. This is great for building basic screens quickly. However, there are some limitations:

Customization: You won't be able to modify the components themselves to fit your specific needs.
Search: Finding the components you need might be more challenging due to the limited selection.
If you're looking to build a more complex app with greater customization, I'd recommend checking out the full version.
