### ISSUE TITLE
[figma] Layout for Action buttons in dialogs may be wrong

### ISSUE THREAD

**Issue by COSMO-EMI** [mui/mui-design-kits#62]
I am using FIGMA MUI file, which is really well made, thanks a lot for your amazing work!

So I wanted to use a dialog, but it wasn't tall enough. I resized it and expected the action buttons to be always in the bottom right corner, which is not what happened: buttons stay at the same place, and I cannot lower them to get a taller content.

Is it really what to expect from a dialog?

**Comment by danilo-leal** [comment]
Hey @COSMO-EMI, thanks for the heads up! We should probably fix this "natively" in the Figma lib.
Fortunately, the fix is very straightforward: 

- Resize the Dialog to the height you want
- Click at the parent **Dialog** component
- Go to the Auto Layout panel
- Click on the three dots horizontal menu
- Change spacing mode from _Packed_ to _Space between_

Here's a gif illustrating the above process:

<img src="https://user-images.githubusercontent.com/67129314/171552597-fef8b207-bfe6-40ef-88ff-0fe564b2d638.gif" styles="width: 200px;" alt=""/>

**Comment by COSMO-EMI** [comment]
Thank you so much, I better understand how layout works now. I knew it was a layout issue, but couldn't figure out what was wrong. Your GIF is really helpful!

**Comment by oliviertassinari** [comment]
@COSMO-EMI Did you consider making the `DialogContent` taller? You could add more padding:

<img width="748" alt="Screenshot 2022-06-12 at 23 54 33" src="https://user-images.githubusercontent.com/3165635/173255233-49e349ce-bd21-497b-909e-a6cb6e0e130e.png">

> We should probably fix this "natively" in the Figma lib

@danilo-leal If we make this change in the library, we would break the auto content expand behavior:

https://user-images.githubusercontent.com/3165635/173255118-d4b321aa-ef05-419f-a857-cb4d138a07dc.mov

If we can only pick one of the two behaviors, I would assume that we should keep the current one, as it optimizes for the designers that follow the predefined spacing constraints.

**Comment by danilo-leal** [comment]
That sounds about right, I guess. The `space-between` approach is good if you want to have a specific height to it rather than let the content inside it determine the end height.

**Comment by COSMO-EMI** [comment]
@oliviertassinari Thanks, this is a lot more flexible that way! Sorry, I started learning Figma two weeks ago, and my tutorials didn't cover these parameters. Your answer is really helpful.
